/*HTML (HYPER TEXT MARKUP LANGUAGE)*/

/*HTML OPTIONS*/
/*STYLE = style-name: Specifies a style template. The default style is DEFAULT.*/

/*List of styles:*/
/*Analysis, Astronomy, Banker, BarrettsBlue, Beige, Brick, Brown, Curve, D3d, Default, */
/*EGDefault,  Education, Electronics, Festival, FestivalPrinter, Gears, Harvest, Minimal,*/
/*HighContrast, Journal, Journal2, Journal3,Listing, Magnify, Meadow, MeadowPrinter, Money,*/
/*NoFontDefault, Normal, NormalPrinter, Ocean, Printer, Rsvp, Rtf, Sasweb, Science, Seaside,*/
/*SeasidePrinter, Sketch, Solutions, Statdoc, Statistical, Theme, Torn, Watercolor, */
/*blockPrint, fancyPrinter, grayscalePrinter, monochromePrinter, SansPrinter, sasdocPrinter,*/
/*serifPrinter etc…  */

/*CONTENTS = 'filename' : Creates a table of contents with links to the body file.*/

/*PAGE = 'filename': Creates a table of contents with links by page number.*/

/*FRAME = 'filename' : Creates a frame that allows you to view the body file and the*/
/*contents or the page file at the same time. If you do not want either the contents or the*/
/*page file, then you don’t need to create a frame file.*/

options HEADTEXT='new';

FILENAME jr "E:\sas_class\ANS\test3.html";

ods listing close;
ods html file='E:\sas_class\ANS\first.html'
		contents='E:\sas_class\ANS\firsttoc.html'
		frame='E:\sas_class\ANS\firstframe.html'
	style=ocean page=jr ;
proc print data=sashelp.class;
id sex;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
run;

proc print data=sashelp.class;
var name height;
id sex;
run;

proc print data=sashelp.class
	style(data)={background=lime foreground=yellow};
var name weight;
id sex;
run;

	proc print data=sashelp.class n;
/*	style(data)={background=lime foreground=yellow};*/
	var name/style(data)={background=blue foreground=yellow just=center width=20}
				style(header)={background=red foreground=black just=center};
	var weight/style(data)={background=red foreground=yellow just=center width=20}
				style(header)={background=brown foreground=black just=center};	 
	id sex/style(data)={background=red foreground=yellow just=center width=20}
				style(header)={background=brown foreground=black just=center};
	sum height/style={background=orange foreground=yellow just=center};
	footnote 'total height is ' ;
	run;

ods html close;
ods listing;

/*RTF (RICH TEXT FORMAT)*/

DATA DS; SET SASHELP.CLASS; RUN;
PROC SORT DATA=DS; BY SEX; RUN;

ODS RTF FILE="E:\sas_class\ANS\Demo.RTF";
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;/*It will create the separate page*/
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS RTF CLOSE;

/**/
/*RTF OPTIONS*/
/*COLUMNS=NO: Prints multiple outputs as no of columns.*/

ODS RTF FILE="E:\sas_class\ANS\Demo.RTF" COLUMNS=2;

PROC MEANS DATA=DS;
RUN;

PROC gchart DATA=DS;
vbar age;
RUN;

PROC PRINT DATA=DS;
var name sex;
RUN;

ODS RTF CLOSE;

/*SASDATE: Default SAS prints date and time on top of RTF output. When this option is on
whenever you open RTF output it change date and time according to system time.*/

ODS RTF FILE="E:\sas_class\ANS\Demo.RTF" sasdate ;
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS RTF CLOSE;

/*BODYTITLE: Puts titles and footnotes in the main part of the RTF document*/
/*instead of in Word headers or footers.*/
ODS RTF FILE="E:\sas_class\ANS\Demo.RTF" BODYTITLE;
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS RTF CLOSE;

/*STYLE = style: Name specifies a style template. The default style is named RTF.*/
ODS RTF FILE="E:\sas_class\ANS\Demo.RTF" STYLE=ocean;
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS RTF CLOSE;

/*STARTPAGE = value: It controls page breaks. The default value is */
/*YES, inserts a break between procedures. */
/*NO, turns off breaks. */
/*NOW, inserts a break at that point.*/

ODS RTF FILE="E:\sas_class\ANS\Demo.RTF" STARTPAGE=yes BODYTITLE;
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
PROC MEANS DATA=DS;
CLASS SEX;
RUN;
ODS RTF CLOSE;

/*CSV (COMMA SEPARATED VALUE)*/
ODS CSV FILE="E:\sas_class\ANS\Demo.CSV";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS CSV CLOSE;

/*XML (EXTENSIBLE MARKUP LANGUAGE)*/

ODS XML FILE="E:\sas_class\ANS\Demo.XML";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS XML CLOSE;


/*PRINTER*/

ODS PRINTER FILE="E:\sas_class\ANS\test.html";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS PRINTER CLOSE;

/*NOTE: Sending ODS PRINTER output to printer "\\server\Canon E510 series Printer".*/
/*NOTE: ODS PRINTER printed 2 pages to C:\Documents and*/
/*      Settings\Administrator\Desktop\sas\Demo.html.*/

/*PCL (PRINTER CONTROL LANGUAGE)*/
ODS PCL FILE="E:\sas_class\ANS\test.pcl";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS PCL CLOSE;

/*PS (POST SCRIPT)*/
ODS PS FILE="E:\sas_class\ANS\test.ps";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS PS CLOSE;

/*MARKUP*/
ODS MARKUP FILE="E:\sas_class\ANS\test.MARKUP";

PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
BY SEX;
PAGEBY SEX;
SUMBY SEX;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS MARKUP CLOSE;


/*ODS TEXT*/
/*Inserts text in output.*/
/*Note: It will works like title and footnotes*/

ODS PDF FILE="E:\sas_class\ANS\Demo.PDF" STARTPAGE=NEVER;
ODS TEXT="This procedure is giving subtotals for height and weight by gender group";
ODS TEXT="This procedure is giving subtotals for height and weight by gender group2";
PROC PRINT DATA=DS NOOBS;
VAR NAME SEX AGE HEIGHT WEIGHT;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
PROC MEANS DATA=DS;
RUN;
ODS PDF TEXT=" Above data is male & Female Data";
ODS PDF CLOSE;

/*ODS PROCLABEL*/
/*PROCLABEL=”Text”, before the procedure*/
/*Whose bookmark you want to modify. Specify the modify information instead of text.*/

ODS PDF FILE="E:\sas_class\ANS\Demo.PDF";
ODS PROCLABEL="Total height & Weight for SASHELP.CLASS Data";
PROC PRINT DATA=SASHELP.CLASS NOOBS;
SUM HEIGHT WEIGHT;
Title c=red f=Arial h=7 ' Indian cricket team';
Title2 j=l c=blue f=Arial h=7 'Indian cricket team names &detals';
Footnote j=l c=green f=calibri h=7 'Generated by BCC ';
RUN;
ODS PROCLABEL="Calculating simple statistics for SASHELP.CLASS Data";
PROC MEANS DATA=SASHELP.CLASS;
RUN;
ODS PDF CLOSE;

*********************;
/*The ODS TRACE statement */
***********************;

/*The ODS TRACE statement tells SAS to print information about output objects in your SAS*/
/*log. There are two ODS TRACE statements: those are ODS TRACE ON, and ODS TRACE OFF. */
/*Syntax:- ODS TRACE ON;*/
			/*PROC STEP;*/
			/*ODS TRACE OFF;*/

DATA DS;
SET SASHELP.CLASS;
RUN;

PROC SORT DATA=DS;
BY SEX;
RUN;

ODS TRACE ON;
PROC MEANS DATA=DS;
BY SEX;
RUN;
ODS TRACE OFF;

/*See the following trace in your SAS log after executing above program. Because it contains*/
/*a BY statement, the MEANS procedure produces one output object for each BY group*/
/*(Sex=F and Sex=M). Notice that these two output objects have the same name, label,*/
/*and template, but different paths.*/

/*The ODS SELECT/EXCLUDE statements*/
/*Once you know the names of the output objects, you can use an ODS SELECT or EXCLUDE stmts */
/*to choose the output objects which you want.*/

ODS TRACE ON;
PROC MEANS DATA=DS;
BY SEX;
ODS SELECT Means.ByGroup2.Summary; /*ODS EXCLUDE Means.ByGroup2.Summary;*/
RUN;
ODS TRACE OFF;
